### ISSUE TITLE
Код ревью №1

### ISSUE THREAD

**Issue by ashokolov** [shevyakhov/WordsFactory#7]
1. Нужно немного поменять структуру пакетов в приложении. Пока что у тебя просто 4 пакета, 3 из которых относятся к UI логике. Логичнее разделить их на пакеты с `логикой` и `ui` (по заданию еще и `data` понадобится), а уже внутри этих пакетов делить классы и группировать их

Также разделение фрагментов в отдельный пакет не очень хорошая практика, потому что с ростом проекта будет и расти наполняемость этой директории. Это означает, что там может быть под 30 фрагментов и будет крайне трудно ориентироваться в структуре проекта. Лучше делить по фичам (к примеру главный экран, экран со словарем и т.п). Тогда под каждый такой экран будет своя папочка и будет легче искать нужный код

2. Строковые константы обязательно нужно располагать в переменных. Это сделано для того, чтобы можно было переиспользовать 1 переменную, а также чтобы нельзя было опечататься во время написания строки. Особенно это касается тех, что находятся в бд (класс `ListConverter`)

3. `binding` обязательно должен быть `nullable` и его нужно не забывать чистить: https://developer.android.com/topic/libraries/view-binding#fragments

4. У тебя очень много логики находится во фрагменте. Фрагмент это вью и в нем должно быть как можно меньше логики. Всю логику, которая может быть связана с `UI` нужно перенести во `ViewModel` и использовать функции из нее

5. Много кода, который не используется, его нужно удалить. Также обращай внимание на эксепшены студии, а также на неиспользуемые конструкции (пишешь `.apply{}` и в блоке ничего не делаешь, значит его можно (и нужно) удалить)

6. `BASE_URL` можно запихнуть в конфиг грэдла и брать оттуда, если не хочется просто переменной (обычно, кстати, в конфиг гредла и пихают)

7. Пиши более развернуто названия переменных. `v` не говорит за себя, а вот `view` уже понятно что такое. Тоже самое касается вью моделей и остальных переменных

**Comment by shevyakhov** [comment]
исправил, перепроверьте пожалуйста

**Comment by ashokolov** [comment]
1. `ViewModel` обычно относится к UI слою приложения, ибо бизнес-классы обычно другие.

2. Располагать элементы лучше не по фрагментам/activity/retrofit и т.п. а по фиче, к которой они относятся.
